exclude: '^ethosu/vela/(tflite|ethos_u55_regs)/'
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.2.0
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
    args: [--line-length=120]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    args: [--max-line-length=120, --extend-ignore=E203]
